apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-secrets
  labels:
    app: spring-boot-api
type: Opaque
stringData:
  key1: {{ randAlphaNum 32 | quote }}
  key2: {{ randAlphaNum 32 | quote }}
