apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api
spec:
  type: ClusterIP
  selector:
    app: spring-boot-api
  ports:
    - name: api
      port: 8081
      targetPort: 8081
    - name: logs
      port: 8082
      targetPort: 8082
    - name: soap
      port: 8083
      targetPort: 8083
